# Generated by Django 5.0.6 on 2024-06-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('foc', models.FloatField()),
                ('total_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ArrowComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArrowComponentPropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('gn', 'Grain'), ('in', 'Inch'), ('gn/in', 'Grain Per Inch')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArrowComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='KnowHow_Arcticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArrowComponentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_value', models.FloatField(null=True)),
                ('non_unit_value', models.CharField(max_length=20, null=True)),
                ('arrow_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrows.arrowcomponent')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arrows.arrowcomponentpropertytype')),
            ],
        ),
        migrations.CreateModel(
            name='ArrowComponentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_start', models.CharField(choices=[('FRONT', 'Shaft Front'), ('BACK', 'Shaft Back')], default='FRONT', max_length=5)),
                ('position_distance_mm', models.FloatField()),
                ('arrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrows.arrow')),
                ('arrow_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrows.arrowcomponent')),
            ],
        ),
        migrations.AddField(
            model_name='arrowcomponent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arrows.arrowcomponenttype'),
        ),
    ]
