# Generated by Django 5.0.6 on 2024-06-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrows', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowHow_Arcticle',
            new_name='KnowHowArticle',
        ),
    ]
