# Generated by Django 5.0.6 on 2024-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrows', '0002_rename_knowhow_arcticle_knowhowarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrowcomponent',
            name='manufacturer',
            field=models.CharField(default='Skylon', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrowcomponent',
            name='name',
            field=models.CharField(default='Edge', max_length=50),
            preserve_default=False,
        ),
    ]
