# Generated by Django 5.0.6 on 2024-06-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrows', '0005_arrow_shaft_length_alter_arrow_foc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrowshaftmodel',
            name='color',
            field=models.CharField(default='black', max_length=30),
        ),
    ]
